version: 2
updates:
  - package-ecosystem: "npm"
    directory: "svelte-source/" # Location of the package manifests
    schedule:
      interval: "daily" # Frequency of updates
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    assignees:
      - "xFutte"
