version: 2
updates:
  - package-ecosystem: "npm" # Specify the package manager you are using
    directory: "svelte-source/" # Location of the package manifests
    schedule:
      interval: "daily" # Frequency of updates
    commit-message:
      prefix: "Dependency: "
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
    # Configure the types of updates you want to include
    allow:
      - dependency-type: "all"
        update-types: ["version-update:semver-minor"]
    # Optionally, configure the reviewers for the PRs
    reviewers:
      - "xFutte"
