version: 2
updates:
  - package-ecosystem: "npm"
    directory: "svelte-source/" # Location of the package manifests
    schedule:
      interval: "daily"
    commit-message:
      prefix: "Dependency: "
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
    allow:
      - dependency-type: "all"
    reviewers:
      - "xFutte"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "npm"
    directory: "svelte-source/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "Security: "
    allow:
      - dependency-type: "direct"
        update-types: ["version-update:semver-major"]
    labels:
      - "security"
    reviewers:
      - "xFutte"
