version: 2
updates:
  - package-ecosystem: "npm"
    directory: "svelte-source/" # Location of the package manifests
    schedule:
      interval: "daily"
    commit-message:
      prefix: "Dependency: "
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
    allow:
      - dependency-type: "all"
    reviewers:
      - "xFutte"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    groups:
      # Group for general updates
      minor-updates:
        patterns:
          - "*"
        update-types: ["minor", "patch"]

  - package-ecosystem: "npm"
    directory: "svelte-source/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "Security: "
    labels:
      - "security"
    allow:
      - dependency-type: "all"
    reviewers:
      - "xFutte"
    groups:
      # Group for security updates
      security-updates:
        patterns:
          - "*"
        update-types: ["major", "minor", "patch"]
        applies-to: "security-updates"
